name: Port Ocean Jira Integration

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Run jira Integration
        uses: port-labs/ocean-sail@v1
        with:
          type: jira
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          port_base_url: "https://api.port.io"
          config: |
            JIRA_HOST: ${{ secrets.JIRA_HOST }}
            ATLASSIANUSEREMAIL: ${{ secrets.atlassianUserEmail }}
            ATLASSIANUSERTOKEN: ${{ secrets.atlassianUserToken }}